### ISSUE TITLE
Hello there .

### ISSUE THREAD

**Issue by vyomanaut** [jernejk/RealTimeFaceApi#1]
sorry this is not an issue but could you please guide me how I can convert this into a windows form or WPF application ?
sorry im new here , but willing to learn

**Comment by jernejk** [comment]
Hi, it shouldn't be too hard to convert this app into a WinForm or WPF application as it predominately relies on OpenCV library. The focus of this project was to demonstrate these features on a real sample and give devs some guidance.

**Comment by maelle64** [comment]
Hello, can you explain a bit more what is facegroupID? Can we put our picture in order for this program to detect and identify our face?

Thank you
