### ISSUE TITLE
FaceGroupID

### ISSUE THREAD

**Issue by maelle64** [jernejk/RealTimeFaceApi#2]
I don't understand what we have to put in order to configure "FaceGroupId" en program.cs, can you explain a little bit more this face?

And how we can train the program in recognizing familiar faces?

Thank you very much

**Comment by maelle64** [comment]
Is FaceGroupId the personGroupId from microsoft API ? It doesn't work even with that, I still have "Getting identity failed"...

**Comment by emilfrancis2027** [comment]
Hi, could yo please explain if you figured it out.

**Comment by jernejk** [comment]
For facial recognition, you first need to create PersonGroup and than PersonGroup Person, which sold the identity.

FaceGroupId is the ID of PersonGroup.

https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395244
