### ISSUE TITLE
Deploy this in .exe

### ISSUE THREAD

**Issue by maelle64** [jernejk/RealTimeFaceApi#3]
Hello, can you explain to me how we can deploy this console App into a .exe in order to use the program on different computers? 

Thank you very much for your help..

**Comment by isonaj** [comment]
To produce an exe, you will need dotnet core 2.2 (min).
From the command-line, type `dotnet publish -c Release -r win10-x64`

This will output your files to: `.\RealTimeFaceApi.Cmd\bin\Release\netcoreapp2.2\win10-x64`
